# Generated by Django 3.0.2 on 2020-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SName', models.CharField(max_length=50)),
                ('TName', models.CharField(max_length=50)),
                ('YearsOne', models.CharField(max_length=20)),
                ('YearsTwo', models.CharField(max_length=20)),
                ('Inscription', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-SName'],
            },
        ),
    ]
