# Generated by Django 3.0.2 on 2020-04-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-Name'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RenameField(
            model_name='people',
            old_name='Inscription',
            new_name='Place',
        ),
        migrations.RemoveField(
            model_name='people',
            name='SName',
        ),
        migrations.RemoveField(
            model_name='people',
            name='TName',
        ),
    ]
